language: r
cache: packages
sudo: required
dist: trusty
warnings_are_errors: false

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libudunits2-dev

r_github_packages:
  - jimhester/robustr
  - jimhester/covr
  - hadley/xml2

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: c0GC9qvEjlKNjB694uBIsm+LvfL0kAfa7V41Ctk8i3sNo4pOQerwybOlCZ/foQMx7yke1UmfmWMfxTc35u8g8+8uH9hBGEHuq+PvR4pnqc6EcgJKrdFPn39ruzH7S4UHy/TaAJgkeXyhM+kjQXCJiX8OK74KJFuumH5LvA7PrHY=

env:
  - TEST_DPLYR_INTERFACE=TRUE
